### ISSUE TITLE
Bff with EF Server Side Sessions: Cannot insert duplicate key row in object 'Session.UserSessions'

### ISSUE THREAD

**Issue by iseneirik** [DuendeSoftware/products#1763]
**Which version of Duende BFF are you using?** 

`2.2.0`

**Which version of .NET are you using?** 

`net8.0`

**Describe the bug**

We have an API running four instances across two machines (two instances each). The API is set up with Bff and `.AddEntityFrameworkServerSideSessions()` and works fine. However, a few times each day (0 - 10) our logs show the following error:

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'Session.UserSessions' with unique index 'IX_UserSessions_ApplicationName_SessionId'. The duplicate key value is (<AppName>, <SessionIdValue>).
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.ReadAsyncExecute(Task task, Object state)
   at Microsoft.Data.SqlClient.SqlDataReader.InvokeAsyncCall[T](SqlDataReaderBaseAsyncCallContext`1 context)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetAsync(Int32 startCommandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
ClientConnectionId:<...>
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetAsync(Int32 startCommandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

I'm speculating that this might be because a user has multiple tabs open, and when they open the browser for the first time after the cookie has expired, they all simultaneously log in, causing a race-condition of sorts. 

**To Reproduce**

Unable to reproduce

**Expected behavior**

I'm not quite sure... I'm uncertain if this error is ignorable or not. I'm assuming the conflict comes from the data already being stored from the call that won the race to Db, if so, maybe something like:

```
if DbUpdateException and the conflicting SessionId results in the same data attempting to be stored, ignore
else rethrow
```

**Log output/exception with stacktrace**

Already in description

**Comment by Erwinvandervalk** [comment]
The actual error can be safely ignored. But the suppression of this log message is now implemented in V3 (#1797), which will be released as an RC1 asap. 

@ctrlaltdan Right now, multiple front-ends isn't officially supported. While I have no doubts you can get it to work, you may run into edge cases like this. Keep an eye out for official support for multiple front-ends in a future release!

**Comment by bamarch** [comment]
> The actual error can be safely ignored. But the suppression of this log message is now implemented in V3 ([#1797](https://github.com/DuendeSoftware/products/pull/1797)), which will be released as an RC1 asap.
> 
> [@ctrlaltdan](https://github.com/ctrlaltdan) Right now, multiple front-ends isn't officially supported. While I have no doubts you can get it to work, you may run into edge cases like this. Keep an eye out for official support for multiple front-ends in a future release!

We are running BFF V3, where `CreateUserSessionAsync` has the exception handling from https://github.com/DuendeSoftware/products/pull/1797

A similar error is bubbling up as an unhandled exception, this time coming from `UpdateUserSessionAsync`.

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'BFF.UserSessions' with unique index 'IX_UserSessions_ApplicationName_SessionId'. The duplicate key value is (/app/, 046411AACE84F009C422AE7BFA8D6E6A).
...
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Duende.Bff.EntityFramework.UserSessionStore.UpdateUserSessionAsync(String key, UserSessionUpdate session, CancellationToken cancellationToken) in /_/bff/src/Bff.EntityFramework/Store/UserSessionStore.cs:line 225
   at Duende.Bff.ServerSideTicketStore.RenewAsync(String key, AuthenticationTicket ticket) in /_/bff/src/Bff/SessionManagement/TicketStore/ServerSideTicketStore.cs:line 125
...
```

<details>
  <summary>Click to expand for full stacktrace</summary>

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'BFF.UserSessions' with unique index 'IX_UserSessions_ApplicationName_SessionId'. The duplicate key value is (/app/, 046411AACE84F009C422AE7BFA8D6E6A).
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.ReadAsyncExecute(Task task, Object state)
   at Microsoft.Data.SqlClient.SqlDataReader.InvokeAsyncCall[T](SqlDataReaderBaseAsyncCallContext`1 context)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnlyAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
ClientConnectionId:36ca7956-2e87-42cf-b301-66c0b3774114
Error Number:2601,State:1,Class:14
ClientConnectionId before routing:a0f4cacd-fcea-4cf2-b778-df6a93c6c480
Routing Destination:bots-ci-group.database.windows.net\e5adbbd6f847,2322
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChangesAsync(IList`1 entries, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Duende.Bff.EntityFramework.UserSessionStore.UpdateUserSessionAsync(String key, UserSessionUpdate session, CancellationToken cancellationToken) in /_/bff/src/Bff.EntityFramework/Store/UserSessionStore.cs:line 225
   at Duende.Bff.ServerSideTicketStore.RenewAsync(String key, AuthenticationTicket ticket) in /_/bff/src/Bff/SessionManagement/TicketStore/ServerSideTicketStore.cs:line 125
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleSignInAsync(ClaimsPrincipal user, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Bots.Identity.Bff.RequestLoggingMiddleware.Invoke(HttpContext context) in /src/Bots.Identity.Bff/RequestLoggingMiddleware.cs:line 24
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
</details>

---

The exception is triggered by a `/signin-oidc` request, resulting in a `500` for the user trying to sign in

This prevents sign in until they clear their cookies, which resolves the issue

We run have a single BFF with multiple frontends when testing

app-test.example.com/....
app-test-1.example.com/...

---

Is the error able to be safely ignored, if exception handling was to be added to `UpdateUserSessionAsync` similarly to `CreateUserSessionAsync`?

Or is the fix to upgrade asap to BFF v4 with support for multiple frontends?

Thanks!
